name: flutter_ios_dark_mode_example
description: Demonstrates how to use the flutter_ios_dark_mode plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_ios_dark_mode:
    path: ../

flutter:
  uses-material-design: false
